// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxLWyIJo7x3TDVkAM4RoLsIY8Ceq-PCJU',
    appId: '1:329968731788:web:3862e321c3d2e526891da9',
    messagingSenderId: '329968731788',
    projectId: 'studentprofile-d4936',
    authDomain: 'studentprofile-d4936.firebaseapp.com',
    storageBucket: 'studentprofile-d4936.firebasestorage.app',
    measurementId: 'G-RECZ74F238',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwG4iex5JmG_Q7dUE7GKhN_hzWPDzZfyQ',
    appId: '1:329968731788:android:618e823184f29827891da9',
    messagingSenderId: '329968731788',
    projectId: 'studentprofile-d4936',
    storageBucket: 'studentprofile-d4936.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdF-uk78f3G2gLWfoj6T_caMoQi2JJsIk',
    appId: '1:329968731788:ios:36c8eedc83020319891da9',
    messagingSenderId: '329968731788',
    projectId: 'studentprofile-d4936',
    storageBucket: 'studentprofile-d4936.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdF-uk78f3G2gLWfoj6T_caMoQi2JJsIk',
    appId: '1:329968731788:ios:36c8eedc83020319891da9',
    messagingSenderId: '329968731788',
    projectId: 'studentprofile-d4936',
    storageBucket: 'studentprofile-d4936.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxLWyIJo7x3TDVkAM4RoLsIY8Ceq-PCJU',
    appId: '1:329968731788:web:24a4d0814c533e3f891da9',
    messagingSenderId: '329968731788',
    projectId: 'studentprofile-d4936',
    authDomain: 'studentprofile-d4936.firebaseapp.com',
    storageBucket: 'studentprofile-d4936.firebasestorage.app',
    measurementId: 'G-KLWM2TR7QB',
  );
}
